[[headers]]
  for = "/*" # 対象ファイルを指定
  [headers.values]
    # ...
    Cache-Control = "no-store" # キャッシュ不可

[[headers]]
  for = "/assets/*"
  [headers.values]
    # 31536000秒=1年間キャッシュ
    Cache-Control = "public, max-age=2678400"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=2678400"