[[headers]]
  for = "/*" # 対象ファイルを指定
  [headers.values]
    # ...
    Cache-Control = "public, max-age=3600" # 1時間のみキャッシュ

[[headers]]
  for = "/assets/*"
  [headers.values]
    # 31日間キャッシュ
    Cache-Control = "public, max-age=2678400"

[[headers]]
  for = "/img/*"
  [headers.values]
    # 31日間キャッシュ
    Cache-Control = "public, max-age=2678400"